### ISSUE TITLE
adding AuthorWork bug

### ISSUE THREAD

**Issue by cschuwey** [LaDHUL/Theatre-de-societe#11]
Bug when adding an AuthorWork, see screen captures

![image](https://cloud.githubusercontent.com/assets/16320890/26686421/20417b24-46ed-11e7-8334-9b4b62e879ff.png)
![image](https://cloud.githubusercontent.com/assets/16320890/26686426/235eed3c-46ed-11e7-8091-e24b90afd1f3.png)

**Comment by loicjaouen** [comment]
Hello @cschuwey , that field is a [URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier) and should comply to the URI scheme.

**Comment by cschuwey** [comment]
My bad ! Sorry.
