### ISSUE TITLE
Unable to enter date

### ISSUE THREAD

**Issue by ghost** [LaDHUL/Theatre-de-societe#24]
In the Person window, this bug happens, making it impossible to select date (the CKEDITOR buttons are taking over the mouse) : 

<img width="706" alt="capture d ecran 2017-12-01 a 18 13 15" src="https://user-images.githubusercontent.com/16320890/33494438-8a1b6f76-d6c3-11e7-9be6-7c09bc7c92a3.png">

**Comment by loicjaouen** [comment]
addressed in https://github.com/dhlab-basel/Knora/issues/676

status: pull request is on its way
next: release on our servers

**Comment by mrivoal** [comment]
@loicjaouen is it fine now with the last release on demo?

**Comment by loicjaouen** [comment]
cleaning-up, fixed since a long while
