### ISSUE TITLE
Label display : @fr rather than @en

### ISSUE THREAD

**Issue by cschuwey** [LaDHUL/Theatre-de-societe#27]
In both platec.unil and salsah-test server, Salsah often displays the @en version of a label rather than @fr version, even when the latter is complete and more correct than the @en version. @fr should be the preferred choice any time.

**Comment by mrivoal** [comment]
Hum... Once you are logged in, as the default language for your team users is set on **@fr**, every class or property with a  **@fr** `rdfs:label` completed should be displayed. But I have to review your commits and update the system with your changes in order for you to notice the changes.

**Comment by cschuwey** [comment]
Apologies. I was checking the label without being logged in. Thanks a lot, good to know !
