### ISSUE TITLE
Notice : slow interface

### ISSUE THREAD

**Issue by cschuwey** [LaDHUL/Theatre-de-societe#28]
Jennifer Ruimi experiences slow suggestion display (4-5 secondes before anything is displayed).

**Comment by mrivoal** [comment]
We will need to have more details on this. 
For which resource? On which browser? Can we have a screen shot to see how many properties of the resource were completed?
By the way, we have already experienced such problems. It is on our radar... just not top priority right now.

**Comment by cschuwey** [comment]
Will ask, but this is also not top priority for us, was merely to mention it.
