### ISSUE TITLE
[Feature request] : add "nickname" 

### ISSUE THREAD

**Issue by cschuwey** [LaDHUL/Theatre-de-societe#30]
Would it possible to add a "pseudonyme" attribute to "Person" ? MinCardinality:0, in case the person got multiple nicknames.

**Comment by mrivoal** [comment]
To create this property, I need:
- `rdfs:label` **@fr** 
- `rdfs:label` **@en** 
- `rdfs:comment` **@fr** 
- `rdfs:comment` **@en** 

And then I can proceed.

**Comment by mrivoal** [comment]
Closed by 116d6f5521433c9a659aa163c489ff816747a020.
