### ISSUE TITLE
[Feature request] : uncertain attribution

### ISSUE THREAD

**Issue by cschuwey** [LaDHUL/Theatre-de-societe#31]
In the "Role" element, add a boolean element to specify if we cannot be certain that the person entered is actually the good one (for instance, when the source only gives the family name)

**Comment by mrivoal** [comment]
To create this property, I need:
- `rdfs:label` **@fr** 
- `rdfs:label` **@en** 
- `rdfs:comment` **@fr** 
- `rdfs:comment` **@en** 

And then I can proceed.

**Comment by cschuwey** [comment]
rdfs:label "Attribution incertaine"@fr
rdfs:label "Dubious attribution"@en
rdfs:comment "L'identification de la personne est incertaine"@fr
rdfs:comment "The person identification is dubious"@en

**Comment by mrivoal** [comment]
Could you also give me a cardinality?

**Comment by cschuwey** [comment]
Is boolean a possibility ? True/false, default false ?

**Comment by mrivoal** [comment]
We can try, yes.

**Comment by mrivoal** [comment]
Closed by 116d6f5521433c9a659aa163c489ff816747a020.
