### ISSUE TITLE
Article de périodique - Revue

### ISSUE THREAD

**Issue by cschuwey** [LaDHUL/Theatre-de-societe#33]
The "Article de périodique" includes a category that is not relevant, because, as it is linked to "Revue", this information should be encoded in the "Revue" object. This is :

- Maison d'édition

However, the "maison d'édition" is not included in the "Revue" object at the moment. Could it be possible to add it ? 

In "Article de périodique", the "Première page" and "Dernière page" could be also melted into a "Pages" field for coherence : the "Quotation" has only a "page" field, even if some quotations are on multiple pages.

**Comment by mrivoal** [comment]
Closed via 2f17dca8bb808297e0b24cf617f6350ad4566671.
