### ISSUE TITLE
Bibliographie : ajout d'une zone "edition en ligne"

### ISSUE THREAD

**Issue by PaulFievre** [LaDHUL/Theatre-de-societe#43]
Certaines publications ont des éditions en ligne.
Les trois cas suivants peuvent se produire :
Edition papier uniquement
Edition en ligne uniquement
Edition papier et en ligne

**Comment by mrivoal** [comment]
@PaulFievre J'ai besoin de davantage d'informations pour définir ce qu'il faut ajouter/modifier dans l'ontologie.

Vous pouvez regardez le schéma du modèle de données [ici](https://github.com/LaDHUL/Theatre-de-societe/blob/master/theatre-societe_model_V4-20180108_MR-uptodate.graphml) (avec [Yed](https://www.yworks.com/products/yed), par exemple) et l'ontologie pour la bibliographie [ici](https://github.com/LaDHUL/Theatre-de-societe/blob/master/theatre-societe-biblio-onto.ttl).

Il faudrait que vous pointiez plus précisément les besoins: 
- quel(s) type(s) de publication est associé à une publication en ligne? (article, journal, livre, chapitre d'ouvrage, manuscrit, etc. ?)
- quelle propriété faut-il ajouter pour pouvoir renseigner un URL? (comment vous attendez-vous à voir cela affiché à l'écran?)

J'imagine qu'il faudrait quelque chose comme cela:

```
###  http://www.knora.org/ontology/0103/theatre-societe-biblio#documentHasOnlinePublication
theatre-societe-biblio:documentHasOnlinePublication rdf:type owl:ObjectProperty ;
                   	rdfs:subPropertyOf knora-base:hasValue ;
	            knora-base:subjectClassConstraint theatre-societe-biblio:Document ;
                    knora-base:objectClassConstraint knora-base:UriValue ;
			rdfs:label "??????"@fr ,
						"?????"@en ;
			rdfs:comment "????????????"@fr ,
						"????????????"@en ;
	                salsah-gui:guiOrder "7"^^xsd:integer ;
	                salsah-gui:guiElement salsah-gui:SimpleText .
```

Mais il faut que je puisse déterminer sur quelle ressource ajouter cette propriété: `Document` , `Publication` ou seulement `JournalArticle` ou `Book` ou `BookChapter`?

Il faudra que vous fournissiez un `rdfs:label` en français et en anglais pour chaque nouvelle propriété: c'est ce qui permet à Salsah d'afficher le nom d'une propriété dans différentes langues.
Et il faut aussi que vous donniez une définition de la propriété via le `rdfs:comment`, en français et en anglais également. C'est ce qui permet de documenter la structure des données.

Quant à la propriété `salsah-gui:guiOrder`, elle permet d'organiser l'ordre d'affichage des différentes propriétés pour une ressource.

**Comment by PaulFievre** [comment]
Vu, je m'en occupe.

Paul

Le lun. 5 nov. 2018 à 12:39, Marion Rivoal <notifications@github.com> a
écrit :

**Comment by loicjaouen** [comment]
à revoir si le demande est renouvelée
