### ISSUE TITLE
"Représentation" as default choice

### ISSUE THREAD

**Issue by cschuwey** [LaDHUL/Theatre-de-societe#9]
Is there a way to put "Représentation" at the top of "Subject class" menu when adding a new object ? As it will be the default entry point, it would save time for users. 
Does the "order" property work on subject classes ? If yes, how to use it in the anthology ? Thanks a lot !

**Comment by mrivoal** [comment]
No, right now, there is no way to have `Représentation` selected as the default class. The `salsah-gui:Order` property is not meant to apply to resource classes. 

However, @loicjaouen has been working on a patch that selects by default the project each user is working on.  That will save you one step and a little bit of time, but you will still need to select `Représentation` by hand.
